# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      - image: circleci/python:3.6.1
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/client-app
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: sudo apt-get install python-dev python-pip
      - run: sudo pip install awscli
      - run: sudo npm install -g gulp-cli
      - run: gulp build
      - deploy:
          name: Deploy to AWS S3
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              aws s3 sync ~/client-app/dist/prod s3://stuyspec
            else
              echo "Not staging so not deploying"
            fi